/**
 * PLEASE DO NOT EDIT THIS FILE (automatically generated from ./schema/props.json)
 */
import {
    Prop,
    Virtual
} from "vue-typed"
import {
    MenuBase
} from "../menu-base"

export abstract class _MenuVerticalBase extends MenuBase {

}