/**
 * PLEASE DO NOT EDIT THIS FILE (automatically generated from ./schema/props.json)
 */
import {
    MenuBase
} from "../menu-base"
import {
    Prop,
    Virtual,
    Mixin
} from "vue-typed"
import * as Vue from "vue"
export abstract class _MenuHorizontalBase extends MenuBase {

    /**
     * Display as secondary menu. See: http://semantic-ui.com/collections/menu.html#secondary-menu
     * 
     * @type {boolean}
     */
    @Prop({
        type: Boolean
    })
    secondary: boolean

}