var gulp = require('gulp')
var buildBase = require('./tasks/build-base')
var buildApi = require('./tasks/build-api')
var buildInterface = require('./tasks/build-interface')
var buildReadme = require('./tasks/build-readme')

gulp.task('build:base', buildBase)
gulp.task('build:api', buildApi)
gulp.task('build:interface', ['build:api'], buildInterface)
gulp.task('build:readme', buildReadme)
gulp.task('build', ['build:base', 'build:interface', 'build:readme'])