/**
 * PLEASE DO NOT EDIT THIS FILE (automatically generated from ./schema/props.json)
 */
import {
    Prop,
    Virtual,
    Mixin
} from "vue-typed"
import * as Vue from "vue"
export abstract class _CheckboxBase extends Virtual < Vue > () {

    /**
     * Input element name
     * 
     * @type {string}
     */
    @Prop({
        type: String
    })
    name: string

    /**
     * v-model binding
     * 
     * @type {any}
     */
    @Prop()
    value: any

    /**
     * Enable interaction with a checkbox
     * 
     * @type {'true' | 'false' | boolean}
     */
    @Prop()
    enabled: 'true' | 'false' | boolean

    /**
     * Checkbox style
     * 
     * @type {'default' | 'slider' | 'toggle'}
     */
    @Prop()
    kind: 'default' | 'slider' | 'toggle'

    /**
     * Checked value
     * 
     * @type {any}
     */
    @Prop()
    val: any

}