/**
 * PLEASE DO NOT EDIT THIS FILE (automatically generated from ./schema/props.json)
 */
import {
    Prop
} from "vue-typed"
import * as Vue from "vue"

export abstract class _MessageBase extends Vue {

    /**
     * Add close icon choose to hide message.
     * 
     * @default false
     * @type {boolean}
     */
    @Prop({
        type: Boolean
    })
    closable: boolean = false

    /**
     * Semantic UI transition on closing message.
     * 
     * @default 'fade'
     * @type {string}
     */
    @Prop({
        type: String
    })
    transition: string = 'fade'

    /**
     * Message variations.
     * 
     * @type {'default' | 'compact' | 'floating'}
     */
    @Prop()
    kind: 'default' | 'compact' | 'floating'

    /**
     * Icon appears on the left of message contens.
     * 
     * @type {string}
     */
    @Prop({
        type: String
    })
    icon: string

}