/**
 * PLEASE DO NOT EDIT THIS FILE (automatically generated from ./schema/props.json)
 */
import {
    Prop,
    Virtual,
    Mixin
} from "vue-typed"
import * as Vue from "vue"
export abstract class _DropdownItemBase extends Virtual < Vue > () {

    /**
     * Dropdown item value
     * 
     * @type {any}
     */
    @Prop()
    value: any

}