/**
 * PLEASE DO NOT EDIT THIS FILE (automatically generated from ./schema/props.json)
 */
import {
    Prop,
    Virtual,
    Mixin
} from "vue-typed"
import * as Vue from "vue"
export abstract class _MenuDropdownBase extends Virtual < Vue > () {

    /**
     * Dropdown title/label.
     * 
     * @type {string}
     */
    @Prop({
        type: String
    })
    label: string

    /**
     * Trigger dropdown on hover.
     * 
     * @type {boolean}
     */
    @Prop({
        type: Boolean
    })
    hover: boolean

    /**
     * Dropdown icon
     * 
     * @default 'dropdown'
     * @type {string}
     */
    @Prop({
        type: String,
        default: 'dropdown'
    })
    icon: string

}