/**
 * PLEASE DO NOT EDIT THIS FILE (automatically generated from ./schema/props.json)
 */
import {
    Prop,
    Virtual
} from "vue-typed"
import {
    FieldBase
} from "../field-base"

export abstract class _FieldBase extends FieldBase {

}