/**
 * PLEASE DO NOT EDIT THIS FILE (automatically generated from ./schema/props.json)
 */
import {
    Calendar
} from "../calendar"
import {
    Prop,
    Virtual,
    Mixin
} from "vue-typed"
import * as Vue from "vue"
export abstract class _TimeBase extends Calendar {

    /**
     * Date format
     * 
     * @type {string}
     */
    @Prop({
        type: String
    })
    format: string

}