/**
 * PLEASE DO NOT EDIT THIS FILE (automatically generated from ./schema/props.json)
 */
import {
    FieldBase
} from "../../../fields/field-base"
import {
    Prop,
    Virtual,
    Mixin
} from "vue-typed"
import * as Vue from "vue"
export abstract class _CalendarBase extends FieldBase {

    /**
     * Input element name
     * 
     * @type {string}
     */
    @Prop({
        type: String
    })
    name: string

    /**
     * Input element placeholder
     * 
     * @type {string}
     */
    @Prop({
        type: String
    })
    placeholder: string

    /**
     * v-model binding
     * 
     * @type {any}
     */
    @Prop()
    value: any

    /**
     * JQuery object or selector for another calendar that represents the start date of a date range
     * 
     * @type {HTMLElement | JQuery | string}
     */
    @Prop()
    rangeStart: HTMLElement | JQuery | string

    /**
     * JQuery object or selector for another calendar that represents the end date of a date range
     * 
     * @type {HTMLElement | JQuery | string}
     */
    @Prop()
    rangeEnd: HTMLElement | JQuery | string

    /**
     * Enable user to clear the value by clicking clear button on the right side of control
     * 
     * @type {boolean}
     */
    @Prop({
        type: Boolean
    })
    canClear: boolean

}