/**
 * PLEASE DO NOT EDIT THIS FILE (automatically generated from ./schema/props.json)
 */
import {
    Numeric
} from "../numeric"
import {
    Prop,
    Virtual,
    Mixin
} from "vue-typed"
import * as Vue from "vue"
export class _CurrencyBase extends Mixin(Numeric) {

    /**
     * Currency sign
     * 
     * @type {string}
     */
    @Prop({
        type: String
    })
    sign: string

    /**
     * Currency sign position
     * 
     * @type {'left' | 'right'}
     */
    @Prop()
    signPos: 'left' | 'right'

}