/**
 * PLEASE DO NOT EDIT THIS FILE (automatically generated from ./schema/props.json)
 */
import {
    Prop,
    Virtual,
    Mixin
} from "vue-typed"
import * as Vue from "vue"
export abstract class _RadioBase extends Virtual < Vue > () {

    /**
     * Input element name
     * 
     * @type {string}
     */
    @Prop({
        type: String
    })
    name: string

    /**
     * Checked value
     * 
     * @type {any}
     */
    @Prop()
    val: any

    /**
     * v-model binding
     * 
     * @type {any}
     */
    @Prop()
    value: any

}