/**
 * PLEASE DO NOT EDIT THIS FILE (automatically generated from ./schema/props.json)
 */
import {
    Prop,
    Virtual,
    Mixin
} from "vue-typed"
import * as Vue from "vue"
export abstract class _MenuBaseBase extends Virtual < Vue > () {

    /**
     * Display menu as sidebar
     * 
     * @type {'vertical' | 'horizontal'}
     */
    @Prop()
    sidebar: 'vertical' | 'horizontal'

    /**
     * JQuery object or selector to be attached as sidebar toggle
     * 
     * @type {HTMLElement | JQuery | string}
     */
    @Prop()
    sidebarToggle: HTMLElement | JQuery | string

}