/**
 * PLEASE DO NOT EDIT THIS FILE (automatically generated from ./schema/props.json)
 */
import {
    Prop
} from "vue-typed"
import {
    FieldBase
} from "../../fields/field-base"

export abstract class _DropdownBase extends FieldBase {

    /**
     * Input element name
     * 
     * @type {string}
     */
    @Prop({
        type: String
    })
    name: string

    /**
     * Input element placeholder
     * 
     * @type {string}
     */
    @Prop({
        type: String
    })
    placeholder: string

    /**
     * v-model binding
     * 
     * @type {any}
     */
    @Prop()
    value: any

    /**
     * A selection dropdown can allow a user to search through a large list of choices.
     * 
     * @type {boolean}
     */
    @Prop({
        type: Boolean
    })
    search: boolean

    /**
     * A selection dropdown can allow multiple selections
     * 
     * @type {boolean}
     */
    @Prop({
        type: Boolean
    })
    multiple: boolean

    /**
     * Css class(es) applied to dropdown component
     * 
     * @type {string}
     */
    @Prop({
        type: String
    })
    css: string

}