/**
 * PLEASE DO NOT EDIT THIS FILE (automatically generated from ./schema/props.json)
 */
import {
    Prop,
    Virtual
} from "vue-typed"
import * as Vue from "vue"

export abstract class _AccordionBase extends Virtual < Vue > () {

    /**
     * Only allow one section open at a time
     * 
     * @default true
     * @type {boolean}
     */
    @Prop({
        type: Boolean
    })
    exclusive: boolean = true

    /**
     * Event on title that will cause accordion to open
     * 
     * @default 'click'
     * @type {string}
     */
    @Prop({
        type: String
    })
    on: string = 'click'

    /**
     * Whether child content opacity should be animated (may cause performance issues with many child elements)
     * 
     * @default true
     * @type {boolean}
     */
    @Prop({
        type: Boolean
    })
    animateChildren: boolean = true

    /**
     * Duration in ms of opening animation
     * 
     * @default 500
     * @type {number}
     */
    @Prop({
        type: Number
    })
    duration: number = 500

    /**
     * Close open nested accordion content when an element closes
     * 
     * @default true
     * @type {boolean}
     */
    @Prop({
        type: Boolean
    })
    closeNested: boolean = true

    /**
     * Allow active sections to collapse
     * 
     * @default true
     * @type {boolean}
     */
    @Prop({
        type: Boolean
    })
    collapsible: boolean = true

}