/**
 * PLEASE DO NOT EDIT THIS FILE (automatically generated from ./schema/props.json)
 */
import {
    Prop,
    Virtual,
    Mixin
} from "vue-typed"
import * as Vue from "vue"
export abstract class _FieldBaseBase extends Virtual < Vue > () {

    /**
     * Field label text
     * 
     * @type {string}
     */
    @Prop({
        type: String
    })
    label: string

    /**
     * Size of field
     * 
     * @type {number}
     */
    @Prop({
        type: Number
    })
    wide: number

    /**
     * Field layout style
     * 
     * @type {'default' | 'grouped' | 'inline'}
     */
    @Prop()
    kind: 'default' | 'grouped' | 'inline'

    /**
     * Disabled field
     * 
     * @default false
     * @type {boolean}
     */
    @Prop({
        type: Boolean,
        default: false
    })
    disabled: boolean

}