/**
 * PLEASE DO NOT EDIT THIS FILE (automatically generated from ./schema/props.json)
 */
import {
    FieldBase
} from "../../fields/field-base"
import {
    Prop,
    Virtual,
    Mixin
} from "vue-typed"
import * as Vue from "vue"
export abstract class _InputBase extends FieldBase {

    /**
     * Input element name
     * 
     * @type {string}
     */
    @Prop({
        type: String
    })
    name: string

    /**
     * Input element placeholder
     * 
     * @type {string}
     */
    @Prop({
        type: String
    })
    placeholder: string

    /**
     * v-model binding
     * 
     * @type {any}
     */
    @Prop()
    value: any

    /**
     * Input element is password element
     * 
     * @type {boolean}
     */
    @Prop({
        type: Boolean
    })
    password: boolean

    /**
     * Name of icon to be displayed
     * 
     * @type {string}
     */
    @Prop({
        type: String
    })
    icon: string

    /**
     * Icon position
     * 
     * @default 'left'
     * @type {'left' | 'right' | string}
     */
    @Prop({
        default: 'left'
    })
    iconPos: 'left' | 'right' | string

    /**
     * Css class(es) applied to input component
     * 
     * @type {string}
     */
    @Prop({
        type: String
    })
    css: string

    /**
     * Select text when receive focus
     * 
     * @default true
     * @type {boolean}
     */
    @Prop({
        type: Boolean,
        default: true
    })
    selectOnFocus: boolean

}