/**
 * PLEASE DO NOT EDIT THIS FILE (automatically generated from ./schema/props.json)
 */
import {
    Prop,
    Virtual
} from "vue-typed"
import {
    FieldBase
} from "../../fields/field-base"

export abstract class _RadioGroupBase extends FieldBase {

    /**
     * Name of radio group
     * 
     * @type {string}
     */
    @Prop({
        type: String
    })
    name: string

}