/**
 * PLEASE DO NOT EDIT THIS FILE (automatically generated from ./schema/props.json)
 */
import {
    FieldBase
} from "../../fields/field-base"
import {
    Prop,
    Virtual,
    Mixin
} from "vue-typed"
import * as Vue from "vue"
export abstract class _RadioGroupBase extends FieldBase {

    /**
     * Name of radio group
     * 
     * @type {string}
     */
    @Prop({
        type: String
    })
    name: string

}